{{- if .Values.extraConfiguration }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ejabberd.fullname" . }}-extra-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $k, $v := .Values.extraConfiguration }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- end }}
